### ISSUE TITLE
abort trap 6 mac os

### ISSUE THREAD

**Issue by Aem1024** [Lauriethefish/Quest-Discord-Presence-Client#3]
When i launch Quest-Discord-Precense-Client i get this error

 at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Quest_Discord_Presence_Client.Client.LoadConfig() in /home/runner/work/Quest-Discord-Presence-Client/Quest-Discord-Presence-Client/src/Client.cs:line 105
   at Quest_Discord_Presence_Client.Client..ctor(String[] args) in /home/runner/work/Quest-Discord-Presence-Client/Quest-Discord-Presence-Client/src/Client.cs:line 34
   at Quest_Discord_Presence_Client.Client.Main(String[] args) in /home/runner/work/Quest-Discord-Presence-Client/Quest-Discord-Presence-Client/src/Client.cs:line 44
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Lauriethefish** [comment]
There are some issues with the client and MacOS currently.
It works for some, but not for others.

In the meanwhile, I'd recommend you use the client by MagMagic instead: https://github.com/madmagic007/Oculus-Quest-Presence
